apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-api-gateway-gateways-argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sources:
  - repoURL: "https://github.com/alija-globaly/sample-argo-app.git"
    targetRevision: "main"
    ref: values    
  - repoURL: "https://github.com/GlobalyHub/GH-infra-and-k8s-charts-central.git"
    targetRevision: "alija-argocd-http-target"          # branch to deploy
    path: "helm-charts/self-managed/aws-gw-api" # path to the Helm chart
    helm:
      valueFiles:
        - $values/gitops-values/staging/alb-aws-gw-argocd.yml   # your argo values file         
  destination:
    server: https://kubernetes.default.svc
    namespace: gateways-argocd
  ignoreDifferences:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    jsonPointers:
    - /spec/parentRefs
    - /status    
  - group: gateway.k8s.aws
    kind: LoadBalancerConfiguration
    jqPathExpressions:
    - '.spec.listenerConfigurations[].alpnPolicy'
    - '.spec.listenerConfigurations[0].defaultCertificate'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true 
      - PrunePropagationPolicy=foreground      
    retry:
      limit: -1            # ← unlimited retries
      backoff:
        duration: 30s      # ← base interval of 30 seconds
        factor: 2
        maxDuration: 10m   # ← raised ceiling to accommodate longer backoff chain      

