server:
  service:
    type: NodePort
    nodePortHttp: 30081
    nodePortHttps: 30443  # required for ALB HTTPS listener

  extraArgs:
    - --insecure

  ingress:
    enabled: false

configs:
  params:
    server.insecure: true