apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-http-argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  sources:
  - repoURL: "https://github.com/alija-globaly/sample-argo-app.git"
    targetRevision: "main"
    ref: values
  - repoURL: "https://github.com/GlobalyHub/GH-infra-and-k8s-charts-central.git"
    targetRevision: "alija-argocd-http-target"
    path: "helm-charts/self-managed/argocd-elb-http-target"
    helm:
      valueFiles:
        - $values/gitops-values/staging/argocd-http-route.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  ignoreDifferences:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    jsonPointers:
    - /spec/parentRefs
    - /status
  - group: gateway.k8s.aws
    kind: LoadBalancerConfiguration
    jqPathExpressions:
    - '.spec.listenerConfigurations[].alpnPolicy'
    - '.spec.listenerConfigurations[0].defaultCertificate'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: -1
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
